//! `cargo xtask dev-up` — auto-bootstrap a local data_dir if missing, then launch
//! `anamnez serve` in the foreground.
//!
//! The bootstrap path is deterministic (FixtureSep, fixed admin email/password) so
//! repeated runs against the same data_dir are no-ops after the first. The daemon
//! uses the recovery-code path to unwrap the passphrase (ANAMNEZ_RECOVERY_CODE).
//!
//! In addition to what `anamnez init` does, dev-up mints a "dev workstation"
//! client cert and inserts the matching `workstation` row before the daemon
//! starts. `dev-seed` then uses this cert to talk HTTP without going through
//! the enrollment exchange (chicken-and-egg).

use std::process::{Command, Stdio};
use std::sync::Arc;

use anamnez_core::bootstrap::{self, BootstrapInputs};
use anamnez_core::code_systems::{loader, repo_code_systems_root};
use anamnez_core::db::Database;
use anamnez_core::env::Environment;
use anamnez_core::ids::WorkstationId;
use anamnez_core::key_custody::ColdBoot;
use anamnez_core::rng::OsRng;
use anamnez_core::test_support::sep::FixtureSep;
use anamnez_core::tls;
use anamnez_core::workstation::{self, Mode, NewWorkstation};
use rcgen::{CertificateParams, DnType, KeyPair};
use secrecy::{ExposeSecret, SecretString};
use sha2::{Digest, Sha256};

use crate::paths;

pub fn run(_args: Vec<String>) -> Result<(), String> {
    let dd = paths::data_dir();
    let db_path = dd.join("anamnez.sqlite");

    if !db_path.exists() {
        eprintln!("dev-up: initializing fresh data_dir at {}", dd.display());
        init(&dd)?;
    } else {
        eprintln!("dev-up: reusing existing data_dir at {}", dd.display());
    }

    // Idempotently seed code-systems lookup tables from the repo CSVs. Production
    // would receive a signed bundle (see SPEC §Storage → Bundle distribution); dev
    // shortcut: load CSVs directly so autocomplete works against `cargo xtask dev-up`.
    ensure_codesystems_loaded(&dd)?;

    let recovery_code = std::fs::read_to_string(paths::recovery_code_file())
        .map_err(|e| format!("read recovery code: {e}"))?;

    eprintln!(
        "dev-up: launching daemon on https://{} (admin: {} / {})",
        paths::BIND,
        paths::ADMIN_EMAIL,
        paths::ADMIN_PASSWORD,
    );
    eprintln!("dev-up: Ctrl-C to stop. In another terminal: `cargo xtask dev-seed`");

    let status = Command::new("cargo")
        .args([
            "run",
            "-p",
            "anamnez",
            "--",
            "serve",
            "--config",
        ])
        .arg(paths::config_toml())
        .arg("--pid-file")
        .arg(paths::pid_file())
        .arg("--bind")
        .arg(paths::BIND)
        .env("ANAMNEZ_RECOVERY_CODE", recovery_code.trim())
        .env("RUST_LOG", "anamnez=info,info")
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .stdin(Stdio::inherit())
        .status()
        .map_err(|e| format!("spawn anamnez serve: {e}"))?;

    // Ctrl-C kills the child with SIGINT — that's the normal way to stop dev-up.
    // Treat any signal-based exit as a clean shutdown; only non-signal non-zero is an error.
    #[cfg(unix)]
    {
        use std::os::unix::process::ExitStatusExt;
        if status.signal().is_some() {
            return Ok(());
        }
    }
    if !status.success() {
        return Err(format!("anamnez serve exited with {status}"));
    }
    Ok(())
}

fn init(dd: &std::path::Path) -> Result<(), String> {
    std::fs::create_dir_all(dd).map_err(io)?;
    std::fs::create_dir_all(dd.join("blobs")).map_err(io)?;
    std::fs::create_dir_all(dd.join("code-systems")).map_err(io)?;

    // Mint TLS materials.
    let pems = tls::mint_server_pems("127.0.0.1").map_err(core)?;

    // Bootstrap: writes DB, admin row, wrap_sep.bin, wrap_recovery.bin, TLS pems.
    let admin_password = SecretString::from(paths::ADMIN_PASSWORD);
    let artifacts = bootstrap::run(BootstrapInputs {
        data_dir: dd,
        environment: Environment::Test,
        admin_email: paths::ADMIN_EMAIL.to_owned(),
        admin_password,
        admin_display_name: paths::ADMIN_DISPLAY_NAME.to_owned(),
        sep: Arc::new(FixtureSep::new()),
        rng: Arc::new(OsRng),
        server_cert_pem: pems.server_cert_pem.clone(),
        server_key_pem: pems.server_key_pem.clone(),
        ca_cert_pem: pems.ca_cert_pem.clone(),
        ca_key_pem: pems.ca_key_pem.clone(),
    })
    .map_err(core)?;

    // Persist the recovery code so `dev-up` runs after the first can set
    // ANAMNEZ_RECOVERY_CODE without prompting.
    std::fs::write(
        paths::recovery_code_file(),
        artifacts.recovery_code.expose_secret(),
    )
    .map_err(io)?;

    // Write config.toml for the daemon. `min_client_version = 0.0.0` matches the
    // workspace crate version so the workstation built from this checkout is never
    // rejected as outdated. A production `anamnez init` writes a stricter floor.
    let cfg = format!(
        r#"# Generated by `cargo xtask dev-up` — do not edit by hand.
environment = "test"
db_path = "{db}"
blob_root = "{blob}"
idle_lock_minutes = 5
code_systems_root = "{cs}"

[min_client_version]
major = 0
minor = 0
patch = 0
"#,
        db = dd.join("anamnez.sqlite").display(),
        blob = dd.join("blobs").display(),
        cs = dd.join("code-systems").display(),
    );
    std::fs::write(paths::config_toml(), cfg).map_err(io)?;

    // Mint a dev workstation cert signed by the CA, insert the workstation row.
    mint_dev_workstation(dd, &pems.ca_cert_pem, &pems.ca_key_pem, artifacts.admin_user_id)?;

    eprintln!("dev-up: bootstrap complete.");
    Ok(())
}

fn mint_dev_workstation(
    dd: &std::path::Path,
    ca_cert_pem: &str,
    ca_key_pem: &str,
    admin: anamnez_core::ids::UserId,
) -> Result<(), String> {
    let id = WorkstationId::new();
    let cn = id.as_uuid().to_string();

    let mut ws_params = CertificateParams::new(Vec::<String>::new())
        .map_err(|e| format!("ws params: {e}"))?;
    ws_params.distinguished_name.push(DnType::CommonName, &cn);
    let ws_key = KeyPair::generate().map_err(|e| format!("ws key: {e}"))?;

    let ca_signer_kp = KeyPair::from_pem(ca_key_pem).map_err(|e| format!("clone ca key: {e}"))?;
    let mut ca_params =
        CertificateParams::new(Vec::<String>::new()).map_err(|e| format!("ca params: {e}"))?;
    ca_params.is_ca = rcgen::IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
    ca_params
        .distinguished_name
        .push(DnType::CommonName, "anamnez-local-ca");
    let signer_ca_cert = ca_params
        .self_signed(&ca_signer_kp)
        .map_err(|e| format!("ca self-sign for signing: {e}"))?;
    let ws_cert = ws_params
        .signed_by(&ws_key, &signer_ca_cert, &ca_signer_kp)
        .map_err(|e| format!("ws signed: {e}"))?;
    let ws_cert_pem = ws_cert.pem();
    let ws_key_pem = ws_key.serialize_pem();

    // Open the DB (recovery path — daemon isn't running yet) and insert the row.
    let cb = ColdBoot::new(Arc::new(FixtureSep::new()));
    let wrap_sep = std::fs::read(dd.join("wrap_sep.bin")).map_err(io)?;
    let passphrase = cb.unwrap_passphrase(&wrap_sep).map_err(core)?;
    let db = Database::open(&dd.join("anamnez.sqlite"), passphrase, Environment::Test)
        .map_err(core)?;

    let cert_serial = uuid::Uuid::new_v4().to_string();
    let cert_fp = sha256_hex(ws_cert_pem.as_bytes());

    workstation::enroll(
        &db,
        admin,
        NewWorkstation {
            label: "Dev Workstation (xtask)".into(),
            mode: Mode::Shared,
            bound_user_id: None,
            cert_serial: cert_serial.clone(),
            cert_fingerprint: cert_fp,
        },
    )
    .map_err(core)?;
    // workstation::enroll() generates its own id — overwrite to match the cert CN.
    db.with_writer(|conn| {
        conn.execute(
            "UPDATE workstation SET id = ?1 WHERE cert_serial = ?2",
            rusqlite::params![id.as_uuid().to_string(), cert_serial],
        )?;
        Ok(())
    })
    .map_err(core)?;

    let wdir = paths::dev_workstation_dir();
    std::fs::create_dir_all(&wdir).map_err(io)?;
    std::fs::write(paths::dev_workstation_cert(), &ws_cert_pem).map_err(io)?;
    std::fs::write(paths::dev_workstation_key(), &ws_key_pem).map_err(io)?;
    // Persist the CA alongside for dev-seed convenience.
    std::fs::write(wdir.join("ca.pem"), ca_cert_pem).map_err(io)?;

    Ok(())
}

fn ensure_codesystems_loaded(dd: &std::path::Path) -> Result<(), String> {
    let cb = ColdBoot::new(Arc::new(FixtureSep::new()));
    let wrap_sep = std::fs::read(dd.join("wrap_sep.bin")).map_err(io)?;
    let passphrase = cb.unwrap_passphrase(&wrap_sep).map_err(core)?;
    let db = Database::open(&dd.join("anamnez.sqlite"), passphrase, Environment::Test)
        .map_err(core)?;

    let already_loaded: bool = db
        .with_reader(|conn| {
            let n: i64 =
                conn.query_row("SELECT COUNT(*) FROM drug_atc", [], |r| r.get(0))?;
            Ok(n > 0)
        })
        .map_err(core)?;
    if already_loaded {
        eprintln!("dev-up: code-systems already loaded, skipping");
        return Ok(());
    }

    let root = repo_code_systems_root();
    if !root.is_dir() {
        return Err(format!(
            "dev-up: code-systems root not found at {} — is this checkout missing the CSVs?",
            root.display(),
        ));
    }

    eprintln!("dev-up: seeding code-systems from {} (one-time)", root.display());
    let reports = db
        .with_writer(|conn| loader::bootstrap_from_repo(conn, &root))
        .map_err(core)?;
    for r in &reports {
        eprintln!(
            "  {:>12}  {:>6} rows",
            r.system.as_str(),
            r.rows_inserted,
        );
    }
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    let out = h.finalize();
    let mut s = String::with_capacity(out.len() * 2);
    for b in out {
        use std::fmt::Write;
        let _ = write!(s, "{b:02x}");
    }
    s
}

fn io(e: std::io::Error) -> String {
    format!("io: {e}")
}

fn core(e: anamnez_core::error::Error) -> String {
    format!("core: {e}")
}
