//! `anamnez init` — first-boot wizard.
//!
//! Lays down the on-disk artifacts described in `anamnez_core::bootstrap`, plus
//! a generated `config.toml` next to them so the operator can immediately
//! run `anamnez serve --config <data_dir>/config.toml`. The recovery code is
//! printed once to stdout — the operator must record it on paper.

use crate::cli::InitArgs;
use crate::passphrase;
use anamnez_core::bootstrap::{self, BootstrapInputs};
use anamnez_core::env::Environment;
use anamnez_core::error::{Error, Result};
use anamnez_core::rng::OsRng;
use anamnez_core::tls;
use secrecy::{ExposeSecret, SecretString};
use std::io::{BufRead, Write};
use std::sync::Arc;

pub fn run(args: InitArgs) -> Result<()> {
    let env = match args.environment.as_str() {
        "production" => Environment::Production,
        "test" => Environment::Test,
        other => {
            return Err(invariant(&format!(
                "--environment must be production|test, got `{other}`"
            )))
        }
    };

    let db_path = args.data_dir.join("anamnez.sqlite");
    if db_path.exists() {
        return Err(Error::Invariant(
            "init: data_dir already contains an anamnez.sqlite",
        ));
    }

    let pems = tls::mint_server_pems(&args.bind_host)?;

    let admin_password = read_password(args.password_stdin)?;

    let artifacts = bootstrap::run(BootstrapInputs {
        data_dir: &args.data_dir,
        environment: env,
        admin_email: args.admin_email.clone(),
        admin_password,
        admin_display_name: args.admin_display_name.clone(),
        sep: passphrase::default_sep(),
        rng: Arc::new(OsRng),
        server_cert_pem: pems.server_cert_pem.clone(),
        server_key_pem: pems.server_key_pem.clone(),
        ca_cert_pem: pems.ca_cert_pem.clone(),
        ca_key_pem: pems.ca_key_pem.clone(),
    })?;

    write_config_toml(&args)?;

    println!();
    println!("anamnez init complete.");
    println!("  data_dir:    {}", args.data_dir.display());
    println!("  admin_email: {}", args.admin_email);
    println!("  admin_id:    {}", artifacts.admin_user_id.as_uuid());
    println!();
    println!("RECOVERY CODE — record this on physical paper. It is the only");
    println!("way to recover the DB after a Mac Studio failure. Not displayed again.");
    println!();
    println!("  {}", artifacts.recovery_code.expose_secret());
    println!();
    Ok(())
}

fn write_config_toml(args: &InitArgs) -> Result<()> {
    let cfg = format!(
        r#"# anamnez daemon config — generated by `anamnez init`.
environment = "{env}"
db_path = "{data_dir}/anamnez.sqlite"
blob_root = "{data_dir}/blobs"
idle_lock_minutes = 10
code_systems_root = "{data_dir}/code-systems"

[min_client_version]
major = 1
minor = 0
patch = 0
"#,
        env = args.environment,
        data_dir = args.data_dir.display(),
    );
    std::fs::create_dir_all(args.data_dir.join("blobs"))?;
    std::fs::create_dir_all(args.data_dir.join("code-systems"))?;
    std::fs::write(args.data_dir.join("config.toml"), cfg)?;
    Ok(())
}

fn read_password(stdin_mode: bool) -> Result<SecretString> {
    if stdin_mode {
        let stdin = std::io::stdin();
        let mut line = String::new();
        stdin.lock().read_line(&mut line)?;
        let trimmed = line.trim_end_matches(['\n', '\r']).to_owned();
        if trimmed.is_empty() {
            return Err(Error::Invariant("init: empty password on stdin"));
        }
        return Ok(SecretString::from(trimmed));
    }
    // Interactive prompt — best-effort echo-off would need an extra crate;
    // for Phase 1 the prompt is plain. Operators who care use --password-stdin.
    print!("Admin password: ");
    std::io::stdout().flush()?;
    let stdin = std::io::stdin();
    let mut line = String::new();
    stdin.lock().read_line(&mut line)?;
    let trimmed = line.trim_end_matches(['\n', '\r']).to_owned();
    if trimmed.is_empty() {
        return Err(Error::Invariant("init: empty password"));
    }
    Ok(SecretString::from(trimmed))
}

fn invariant(s: &str) -> Error {
    Error::Invariant(Box::leak(s.to_owned().into_boxed_str()))
}
